export const OPEN_SOCKET = 'OPEN_SOCKET';

// Room
export const JOIN_A_ROOM = 'JOIN_A_ROOM';
export const SET_ROOM_ERROR = 'SET_ROOM_ERROR';
export const SET_ROOM_INFO = 'SET_ROOM_INFO';
export const SET_ROOM_SEAT_INFO = 'SET_ROOM_SEAT_INFO';
export const UPDATE_ROOM_INFO = 'UPDATE_ROOM_INFO';
export const SET_ROOM_CURRENT_PLAYER_SELECTED_CARD =
  'SET_ROOM_CURRENT_PLAYER_SELECTED_CARD';
export const SET_ROOM_CURRENT_PLAYER_FINAL_CARD =
  'SET_ROOM_CURRENT_PLAYER_FINAL_CARD';

// Player
export const PICK_A_CARD_FOR_SEAT = 'PICK_A_CARD_FOR_SEAT';
export const PICK_A_CARD_FOR_PRIORITY = 'PICK_A_CARD_FOR_PRIORITY';
export const SET_PLAYER_ERROR = 'SET_PLAYER_ERROR';
export const SET_PLAYER_INFO = 'SET_PLAYER_INFO';
export const UPDATE_PLAYER_INFO = 'UPDATE_PLAYER_INFO';
export const UPDATE_PLAYER_CARD_ORDER = 'UPDATE_PLAYER_CARD_ORDER';
